In [1]:
import numpy as np 

In [5]:
a1 = np.array( [[.114, .572, .636, .28], [.134, .528, 1.634, .352],[.286, 1.63, 1.436, .246], [.48, .914, .52, .106]])

In [6]:
a2 = np.array( [[.21, .602, .658, .77], [.626, 1.58, 2.62, .992],[.744, 2.664, 1.734, .626], [.972, .798, .43, .212]])

In [7]:
a = np.empty([4, 4, 2])
a[ :, :, 0] = a1 +
a[ :, :, 1] = a2

In [10]:
b1 = np.array( [[.1, .5, .6, .3], [.2, .4, .8, .1],[.1, .3, .7, .2], [.3, .1, .2, .1]])

In [12]:
a1+b1

array([[0.214, 1.072, 1.236, 0.58 ],
       [0.334, 0.928, 2.434, 0.452],
       [0.386, 1.93 , 2.136, 0.446],
       [0.78 , 1.014, 0.72 , 0.206]])

In [13]:
a2 + b1

array([[0.31 , 1.102, 1.258, 1.07 ],
       [0.826, 1.98 , 3.42 , 1.092],
       [0.844, 2.964, 2.434, 0.826],
       [1.272, 0.898, 0.63 , 0.312]])

In [31]:
h2 = a1+a2+b1

In [32]:
H = h2.reshape([-1])

In [33]:
w2 = np.array([.1, .2, .3, .2, .4, .6, .7, .1, .1, .2, .5, .3, .1, .2, .6, .9])

In [36]:
m = np.sum( w2* H ) + .3 

In [38]:
y_hat = np.exp( m) / (1+np.exp(m))

In [39]:
-1/y_hat

-1.0000062771154894

In [40]:
.999*(1-.999)*-1/y_hat * w2

array([-9.99006271e-05, -1.99801254e-04, -2.99701881e-04, -1.99801254e-04,
       -3.99602508e-04, -5.99403763e-04, -6.99304390e-04, -9.99006271e-05,
       -9.99006271e-05, -1.99801254e-04, -4.99503135e-04, -2.99701881e-04,
       -9.99006271e-05, -1.99801254e-04, -5.99403763e-04, -8.99105644e-04])